### PR TITLE
Support for Solidity 0.8.5

### PR DESCRIPTION
**Pull request by blitz-1306**
## Changes
- [x] Updated dependencies.
- [x] Added support for **Solidity 0.8.5** release on compile level (`solc@0.8.5`). No changes were needed on AST level.
- [x] Tweaked AST-to-source writing components to respect the changes.
- [x] Tweaked related test suites and samples.

## Related links
- [Solidity 0.8.5 release notes](https://github.com/ethereum/solidity/releases/tag/v0.8.5)
- [Solidity 0.8.5 release blog post](https://blog.soliditylang.org/2021/06/10/solidity-0.8.5-release-announcement/)

Regards.

### CODE REVIEW

**Comment by axic** [comment]
Any chance of getting this merged and perhaps also support for 0.8.6? :wink:

**Comment by blitz-1306** [comment]
@axic Hello. I'm currently at vacation until 1st of July. I will eventually merge this and implement support for 0.8.6. I this is urgently needed, we will consider. Also @cd1m0 can do this aside from me.

**Review by cd1m0 — APPROVED** [review]

**Comment by cd1m0** [comment]
@axic I got you fam ;). I can merge this, but will wait for Pavel to come back for 0.8.6 support as he is the master of this land (solc-typed-ast)

**Comment by axic** [comment]
Awesome, thank you!

Will wait for @blitz-1306 to come back with 0.8.6 and a new scribble release, lets hope we do not release 0.8.7 before that 😉

**Pull request merged**
